from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemyseeder import ResolvingSeeder

from app import config
from database.models import Base


class Seeder:
    def __init__(self):
        self.engine = create_engine(
            config.mysql_uri, pool_recycle=280, pool_pre_ping=True, pool_size=25
        )
        self.Session = sessionmaker(bind=self.engine)
        Base.metadata.create_all(self.engine)

    def add_issues(self):
        try:
            session = self.Session()
            seeder = ResolvingSeeder(session)
            seeder.load_entities_from_data_dict(
                {
                    "target_class": "database.models:Issue",
                    "data": [
                        {
                            "name": "nasal congestion",
                            "clarifying_questions": [
                                "How long have you faced this issue for?",
                                "Do you have any fever? If yes, since when do you have fever?",
                                "Do you have these symptoms like severe headache, eye lid swelling or painful eye movement?",
                                "Do you have trauma with nose bleed?",
                            ],
                        },
                        {
                            "name": "chest pain",
                            "clarifying_questions": [
                                "How long have you faced this issue for?",
                                "How bad is it on a scale of 1-10?",
                                "Any shortness of breath?",
                                "Is it worse while walking around?",
                                "Have you had this in the past as well?",
                                "Did you travel for more than 1 hour in the past month?",
                                "Have you used any contraceptives?",
                                "Do you have leg pain or swelling?",
                                "Prior PE or DVT?",
                                "Did you try inhaler?",
                                "Does breathing makes it worse?",
                                "Do you have cough?",
                                "Is it intermittent or constant?",
                            ],
                        },
                        {
                            "name": "diarrhea",
                            "clarifying_questions": [
                                "How long have you faced this issue for?",
                                "Do you travel to foreign countries?",
                                "Have you used antibiotics in the past 2 months?",
                                "Are you a hiker?",
                                "Do you have abdominal pain and tenderness?",
                                "Are your vital signs abnormal?",
                                "Do you have medical co-morbidities?",
                                "Are you immunocompromised?",
                                "Do you see blood in your stool?",
                                "Do you have any fever?",
                                "MSWM?",
                            ],
                        },
                        {
                            "name": "ear pain",
                            "clarifying_questions": [
                                "How much does it hurt on a scale of 1-10?",
                                "Do you feel loss of hearing?",
                                "Any drainage?",
                                "Do they hurt when you push on them?",
                                "Did you have sinus congestion within last month?",
                            ],
                        },
                        {
                            "name": "headache",
                            "clarifying_questions": [
                                "Worst at onset?",
                                "Do you have frontal side head pain, jaw pain while chewing?",
                                "Do you have eye pain when vision changes?",
                                "Hearing tinnitus?",
                                "Is this one sided weakness?",
                            ],
                        },
                        {
                            "name": "urinary tract infection",
                            "clarifying_questions": [
                                "How long have you faced this?",
                                "Pain with urination?",
                                "Increased frequency?",
                                "Urgency for urination?",
                                "Any back pain?",
                                "Do you have any fever?",
                                "Male penile discharge?",
                                "Male weak stream?",
                            ],
                        },
                        {"name": "back pain", "clarifying_questions": []},
                        {"name": "finger pain", "clarifying_questions": []},
                        {"name": "rash", "clarifying_questions": []},
                        {"name": "cough", "clarifying_questions": []},
                        {"name": "nausea and diarrhea", "clarifying_questions": []},
                        {"name": "vaginal discharge", "clarifying_questions": []},
                        {"name": "skin bumps", "clarifying_questions": []},
                        {"name": "head trauma", "clarifying_questions": []},
                        {"name": "weakness", "clarifying_questions": []},
                        {
                            "name": "gastrointestinal and respiratory symptoms",
                            "clarifying_questions": [],
                        },
                        {"name": "brain fog", "clarifying_questions": []},
                        {"name": "pink eye", "clarifying_questions": []},
                        {"name": "ear clogged", "clarifying_questions": []},
                        {"name": "medication refill", "clarifying_questions": []},
                        {
                            "name": "sore throat",
                            "clarifying_questions": [
                                "How long have you faced this?",
                                "Unable to drink or unable to breath?",
                                "Do you have any fever?",
                                "Do you have any other symptoms as well like cough?",
                                "Do you see any white spots?",
                                "Do you feel fatigue?",
                                "At STD risk?",
                                "Multiple sx?",
                                "Postnasal drip?",
                                "Swelling of lymph nodes?",
                                "Neck Pain, Trismus, Drooling?",
                            ],
                        },
                        {
                            "name": "abdominal pain",
                            "clarifying_questions": [
                                "Is it constant?",
                                "Is it crampy or not?",
                                "Feeling nausea?",
                                "Pain in lower quadrant of your tummy?",
                                "Do you have any fever?",
                                "When was your last bowel movement?",
                                "Any past abdominal surgeries which i don't know about yet?",
                                "Any past heart history which i don't know about yet?",
                                "Are you drinking more than 2 drinks per day?",
                                "Does it hurt to push on a part of the stomach?",
                                "Any vaginal bleeding? *Only for female patients",
                                "Do you have dysuria i.e. painful or difficult urination?",
                                "Are you using any steroids?",
                                "Nil per OS i.e. withholding oral food and fluids?",
                                "Do you have any mental disability?",
                                "How much pain do you experience on a scale of 1-10?",
                            ],
                        },
                        {
                            "name": "hand pain",
                            "clarifying_questions": [
                                "Unable to straighten finger tip after injury?",
                                "Do you feel pain in little finger knuckle or hand after injury?",
                                "Do you feel pain in finger tip after injury?",
                                "Do you feel pain in back of the thumb after injury?",
                                "Pain or swelling, on the palm side of the end of the finger, pain with straightening the finger with swelling?",
                                "Back of the thumb pain with curling the thumb and stretching it?",
                            ],
                        },
                    ],
                },
            )
        finally:
            session.commit()
            session.close()

    def add_medicines(self):
        try:
            session = self.Session()
            seeder = ResolvingSeeder(session)
            seeder.load_entities_from_data_dict(
                {
                    "target_class": "database.models:Medicine",
                    "data": [
                        {
                            "name": "Albuterol ",
                            "type": "Inhaler",
                            "minimum_age": 18,
                            "is_allowed_for_pregnant": True,
                        },
                        {
                            "name": "Amitriptyline",
                            "type": "Antidepressant",
                            "minimum_age": 12,
                            "is_allowed_for_pregnant": True,
                            "avoid_in_conditions": "myocardial, glaucoma, MAO, seizures\t",
                        },
                        {
                            "name": "Amoxicillin",
                            "type": "Antibiotics",
                            "minimum_age": 1,
                            "is_allowed_for_pregnant": False,
                            "avoid_in_allergies": "penicillin",
                            "avoid_in_conditions": "kidney",
                            "avoid_in_medications": "methotrexate",
                            "instructions": "Wait to take 7 days from symptom onset.",
                        },
                        {
                            "name": "Augmentin",
                            "type": "Antibiotics",
                            "minimum_age": 18,
                            "is_allowed_for_pregnant": True,
                            "avoid_in_allergies": "penicillin",
                            "avoid_in_conditions": "kidney, liver, mononucleosis",
                            "avoid_in_medications": "methotrexate, tetracycline",
                        },
                        {
                            "name": "Azithromycin",
                            "type": "Antibiotics",
                            "minimum_age": 14,
                            "is_allowed_for_pregnant": False,
                        },
                        {
                            "name": "Bicillin L-A",
                            "type": "Antibiotics",
                            "minimum_age": 10,
                            "is_allowed_for_pregnant": False,
                        },
                        {
                            "name": "Cefdinir",
                            "type": "Antibiotics",
                            "minimum_age": 1,
                            "is_allowed_for_pregnant": True,
                            "avoid_in_allergies": "penicillin",
                            "avoid_in_conditions": "kidney",
                        },
                        {
                            "name": "Ceftriaxone",
                            "type": "Antibiotics",
                            "minimum_age": 14,
                            "is_allowed_for_pregnant": False,
                        },
                        {
                            "name": "Cephalexin",
                            "type": "Antibiotics",
                            "minimum_age": 1,
                            "is_allowed_for_pregnant": False,
                        },
                        {
                            "name": "Ciprofloxacin",
                            "type": "Antibiotics",
                            "minimum_age": 14,
                            "is_allowed_for_pregnant": False,
                            "avoid_in_allergies": "penicillin",
                            "avoid_in_conditions": "kidney",
                            "avoid_in_medications": "methotrexate",
                        },
                        {
                            "name": "Claritin",
                            "type": "Antihistamines",
                            "minimum_age": 2,
                            "allowed_gender": "Female",
                            "is_allowed_for_pregnant": False,
                            "avoid_in_allergies": "loratadine",
                            "avoid_in_conditions": "liver, kidney",
                            "avoid_in_medications": "ketoconazole, erythromycin, cimetidine, bronchodilators",
                        },
                        {
                            "name": "Clindamycin",
                            "type": "Antibiotics",
                            "minimum_age": 1,
                            "is_allowed_for_pregnant": False,
                            "avoid_in_allergies": "lincomycin, liver",
                            "avoid_in_conditions": "colitis, liver, kidney",
                        },
                        {
                            "name": "Clotrimazole Cream",
                            "type": "Antifungal",
                            "minimum_age": 2,
                            "allowed_gender": "Female",
                            "is_allowed_for_pregnant": True,
                            "avoid_in_allergies": "clotrimazole",
                        },
                        {
                            "name": "Cortisporin Drops",
                            "type": "Antibiotics",
                            "minimum_age": 14,
                            "is_allowed_for_pregnant": True,
                        },
                        {
                            "name": "Covid Test",
                            "type": "Test",
                            "minimum_age": 1,
                            "is_allowed_for_pregnant": True,
                        },
                        {
                            "name": "Cromylin Sprays",
                            "type": "Antihistamines",
                            "minimum_age": 2,
                            "is_allowed_for_pregnant": True,
                            "avoid_in_allergies": "fluticasone propionate",
                            "avoid_in_surgeries": "abdominal",
                        },
                        {
                            "name": "Doxycycline",
                            "type": "Antibiotics",
                            "minimum_age": 1,
                            "is_allowed_for_pregnant": False,
                            "avoid_in_allergies": "tetracycline",
                            "avoid_in_conditions": "liver, kidney",
                            "avoid_in_medications": "antacids, warfarin, penicillin antibiotics",
                            "instructions": "Wait to take 7 days from symptom onset.",
                        },
                        {
                            "name": "EKG",
                            "type": "Procedure",
                            "minimum_age": 1,
                            "is_allowed_for_pregnant": True,
                        },
                        {
                            "name": "Electrocardiogram Test",
                            "type": "Test",
                            "minimum_age": 1,
                            "is_allowed_for_pregnant": True,
                        },
                        {
                            "name": "Excedrin",
                            "type": "Painkiller",
                            "minimum_age": 12,
                            "is_allowed_for_pregnant": True,
                            "avoid_in_conditions": "stomach ulcers",
                            "avoid_in_medications": "aspirin, naproxen, celecoxib",
                        },
                        {
                            "name": "Fioricet",
                            "type": "Drug",
                            "minimum_age": 12,
                            "is_allowed_for_pregnant": True,
                            "avoid_in_conditions": "porphyria",
                            "avoid_in_medications": "ergotamine, triptans",
                        },
                        {
                            "name": "Flonase",
                            "type": "Nasal sprays",
                            "minimum_age": 2,
                            "is_allowed_for_pregnant": True,
                            "avoid_in_allergies": "fluticasone propionate",
                            "avoid_in_surgeries": "abdominal",
                        },
                        {
                            "name": "Flu Test",
                            "type": "Test",
                            "minimum_age": 1,
                            "is_allowed_for_pregnant": True,
                        },
                        {
                            "name": "Fluconazole",
                            "type": "Nasal sprays",
                            "minimum_age": 18,
                            "allowed_gender": "Female",
                            "is_allowed_for_pregnant": False,
                            "avoid_in_allergies": "fluticasone propionate",
                            "avoid_in_surgeries": "abdominal",
                        },
                        {
                            "name": "Hydrocortisone",
                            "type": "Corticosteroid",
                            "minimum_age": 14,
                            "is_allowed_for_pregnant": False,
                        },
                        {
                            "name": "Imitrex",
                            "type": "Drug",
                            "minimum_age": 18,
                            "is_allowed_for_pregnant": False,
                            "avoid_in_conditions": "ischemic heart disease, uncontrolled hypertension, peripheral vascular disease, hemiplegic or basilar migraine\t",
                            "avoid_in_medications": "ergotamine, MAO, triptans\t",
                            "avoid_in_surgeries": "gastrointestinal",
                        },
                        {
                            "name": "Levofloxacin",
                            "type": "Antibiotics",
                            "minimum_age": 1,
                            "is_allowed_for_pregnant": False,
                            "avoid_in_allergies": "fluoroquinolones, tendon problems, myasthenia gravis",
                            "avoid_in_conditions": "liver, kidney, epilepsy, diabetes",
                            "avoid_in_medications": "methotrexate, tetracycline, warfarin, antacids, sucralfate",
                            "instructions": "Wait to take 7 days from symptom onset.",
                        },
                        {
                            "name": "Lidocaine",
                            "type": "Antibiotics",
                            "minimum_age": 1,
                            "is_allowed_for_pregnant": False,
                        },
                        {
                            "name": "Loperamide",
                            "type": "Imodium",
                            "minimum_age": 14,
                            "is_allowed_for_pregnant": False,
                        },
                        {
                            "name": "Metoprolol",
                            "type": "Beta-blocker",
                            "minimum_age": 1,
                            "is_allowed_for_pregnant": True,
                            "avoid_in_conditions": "bradycardia, heart block, cardiogenic shock\t",
                            "avoid_in_medications": "beta-blocker",
                        },
                        {
                            "name": "Metronidazole",
                            "type": "Antibiotics",
                            "minimum_age": 0,
                            "is_allowed_for_pregnant": False,
                        },
                        {
                            "name": "Migranal",
                            "type": "Drug",
                            "minimum_age": 18,
                            "is_allowed_for_pregnant": False,
                            "avoid_in_conditions": "uncontrolled hypertension, ischemic heart disease",
                            "avoid_in_medications": "ergotamine, triptans",
                        },
                        {
                            "name": "Mono Test",
                            "type": "Test",
                            "minimum_age": 1,
                            "is_allowed_for_pregnant": True,
                        },
                        {
                            "name": "Motrin",
                            "type": "Painkiller",
                            "minimum_age": 1,
                            "is_allowed_for_pregnant": True,
                            "avoid_in_conditions": "ulcers",
                            "avoid_in_medications": "aspirin, naproxen, celecoxib",
                        },
                        {
                            "name": "Mucinex",
                            "type": "Decongestants",
                            "minimum_age": 4,
                            "is_allowed_for_pregnant": False,
                            "avoid_in_allergies": "sympathomimetic amines",
                            "avoid_in_conditions": "diabetes, hypertension, glaucoma, heart, MAOI, thyroid",
                            "avoid_in_medications": "beta-blockers, tricyclic antidepressants, digoxin, asthma medication",
                            "avoid_in_surgeries": "abdominal",
                        },
                        {
                            "name": "Naproxen",
                            "type": "Painkiller",
                            "minimum_age": 12,
                            "is_allowed_for_pregnant": True,
                            "avoid_in_conditions": "ulcers",
                            "avoid_in_medications": "aspirin, Ibuprofen",
                        },
                        {
                            "name": "Nitazoxanide",
                            "type": "Antibiotics",
                            "minimum_age": 1,
                            "is_allowed_for_pregnant": False,
                        },
                        {
                            "name": "O2 Saturation Test",
                            "type": "Test",
                            "minimum_age": 1,
                            "is_allowed_for_pregnant": True,
                        },
                        {
                            "name": "Pepcid",
                            "type": "Antacid",
                            "minimum_age": 1,
                            "is_allowed_for_pregnant": True,
                        },
                        {
                            "name": "Phenylephrine",
                            "type": "Decongestants",
                            "minimum_age": 4,
                            "is_allowed_for_pregnant": False,
                            "avoid_in_allergies": "sympathomimetic amines",
                            "avoid_in_conditions": "diabetes, hypertension, glaucoma, heart, thyroid",
                            "avoid_in_medications": "MAO inhibitors, beta-blockers, tricyclic antidepressants, digoxin, asthma medication",
                            "avoid_in_surgeries": "abdominal",
                        },
                        {
                            "name": "Prednisone",
                            "type": "Corticosteroid",
                            "minimum_age": 1,
                            "is_allowed_for_pregnant": True,
                            "avoid_in_conditions": "fungal infections, systemic viral infections, uncontrolled hypertension, osteoporosis\t",
                        },
                        {
                            "name": "Pregnancy test",
                            "type": "Test",
                            "minimum_age": 1,
                            "is_allowed_for_pregnant": True,
                        },
                        {
                            "name": "Prilosec",
                            "type": "Inhibitor",
                            "minimum_age": 1,
                            "is_allowed_for_pregnant": True,
                        },
                        {
                            "name": "Prochlorperazine",
                            "type": "Antiemetic",
                            "minimum_age": 2,
                            "is_allowed_for_pregnant": True,
                            "avoid_in_conditions": "coma, subcortical brain damage, Reye's syndrome\t",
                            "avoid_in_surgeries": "gastrointestinal",
                        },
                        {
                            "name": "Propranolol",
                            "type": "Beta-blocker",
                            "minimum_age": 18,
                            "is_allowed_for_pregnant": True,
                            "avoid_in_conditions": "bradycardia, heart block, cardiogenic shock\t",
                            "avoid_in_medications": "beta-blocker",
                        },
                        {
                            "name": "Pseudoephedrine",
                            "type": "Decongestants",
                            "minimum_age": 4,
                            "is_allowed_for_pregnant": False,
                            "avoid_in_allergies": "sympathomimetic amines",
                            "avoid_in_conditions": "diabetes, hypertension, glaucoma, heart, MAOI, thyroid",
                            "avoid_in_medications": "beta-blockers, tricyclic antidepressants, digoxin, asthma medication",
                            "avoid_in_surgeries": "abdominal",
                        },
                        {
                            "name": "Refer an ENT specialist",
                            "type": "Refer",
                            "minimum_age": 0,
                            "is_allowed_for_pregnant": False,
                        },
                        {
                            "name": "Refer to the Emergency Room (ER)\n",
                            "type": "Refer",
                            "minimum_age": 1,
                            "is_allowed_for_pregnant": True,
                        },
                        {
                            "name": "Reglan",
                            "type": "Antiemetic",
                            "minimum_age": 1,
                            "is_allowed_for_pregnant": True,
                            "avoid_in_conditions": "gastrointestinal hemorrhage, mechanical obstruction, perforation\t",
                            "avoid_in_surgeries": "gastrointestinal",
                        },
                        {
                            "name": "Saline mist",
                            "type": "Nasal sprays",
                            "minimum_age": 2,
                            "allowed_gender": "Female",
                            "is_allowed_for_pregnant": True,
                        },
                        {
                            "name": "STD Test",
                            "type": "Test",
                            "minimum_age": 1,
                            "is_allowed_for_pregnant": True,
                        },
                        {
                            "name": "Strep Test",
                            "type": "Test",
                            "minimum_age": 1,
                            "is_allowed_for_pregnant": True,
                        },
                        {
                            "name": "Sucralfate",
                            "type": "Drug",
                            "minimum_age": 1,
                            "is_allowed_for_pregnant": True,
                        },
                        {
                            "name": "Tinidazole",
                            "type": "Antibiotics",
                            "minimum_age": 3,
                            "is_allowed_for_pregnant": False,
                        },
                        {
                            "name": "Tylenol",
                            "type": "Painkiller",
                            "minimum_age": 1,
                            "is_allowed_for_pregnant": True,
                            "avoid_in_conditions": "liver",
                        },
                        {
                            "name": "Urinalysis Test",
                            "type": "Test",
                            "minimum_age": 1,
                            "is_allowed_for_pregnant": True,
                        },
                        {
                            "name": "Refer an Urologist",
                            "type": "Refer",
                            "minimum_age": 1,
                            "is_allowed_for_pregnant": True,
                        },
                        {
                            "name": "Ventolyn",
                            "type": "Inhalers",
                            "minimum_age": 4,
                            "is_allowed_for_pregnant": True,
                        },
                        {
                            "name": "Wax removal",
                            "type": "Procedure",
                            "minimum_age": 1,
                            "is_allowed_for_pregnant": True,
                        },
                        {
                            "name": "X-Ray Test",
                            "type": "Test",
                            "minimum_age": 1,
                            "is_allowed_for_pregnant": True,
                        },
                        {
                            "name": "Xyzal",
                            "type": "Antihistamines",
                            "minimum_age": 2,
                            "is_allowed_for_pregnant": False,
                            "avoid_in_allergies": "levocetirizine",
                            "avoid_in_conditions": "liver, kidney",
                            "avoid_in_medications": "ketoconazole, erythromycin, cimetidine, bronch",
                        },
                        {
                            "name": "Zofran",
                            "type": "Drug",
                            "minimum_age": 1,
                            "is_allowed_for_pregnant": True,
                        },
                        {
                            "name": "Zyrtec",
                            "type": "Antihistamines",
                            "minimum_age": 2,
                            "is_allowed_for_pregnant": False,
                            "avoid_in_allergies": "cetirizine",
                            "avoid_in_conditions": "liver, kidney",
                            "avoid_in_medications": "ketoconazole, erythromycin, cimetidine, bronchodilators",
                        },
                    ],
                },
            )
        finally:
            session.commit()
            session.close()

    def seed(self):
        # self.add_issues()
        self.add_medicines()

    def close(self):
        self.engine.dispose()
